### ISSUE TITLE
Requesting updates to "shared/adb-provision/adb-provision.md" file 

### ISSUE THREAD

**Issue by chrishoina** [oracle-livelabs/adb#212]
For the shared file located at this path `shared/adb-provision/adb-provision.md`, the database display name differs from what is allowed in the current version of OCI. In the current lab, users are able to choose a display name with whitespace characters. However, in the latest version of OCI, when selecting a display name (for an ADW in this case), whitespaces are not allowed. 

See attached images for reference: 
<img width="1440" alt="Screenshot 2023-08-03 at 4 07 20 PM" src="https://github.com/oracle-livelabs/adb/assets/61287997/2f9b90b6-2968-413d-a71e-10594cb42bf1">
<img width="1440" alt="Screenshot 2023-08-03 at 4 07 14 PM" src="https://github.com/oracle-livelabs/adb/assets/61287997/f88b9522-60cf-43f9-97b6-5978b4311d71">
<img width="1440" alt="Screenshot 2023-08-03 at 4 07 08 PM" src="https://github.com/oracle-livelabs/adb/assets/61287997/75efee98-61a4-4150-b956-0d7556400c53">
<img width="1440" alt="Screenshot 2023-08-03 at 4 06 56 PM" src="https://github.com/oracle-livelabs/adb/assets/61287997/a94d1362-69a8-48b3-9572-4a064685df36">

**Comment by anooshapilli** [comment]
@chrishoina Thanks for letting us know.
@greenrick - Could you check and update the lab?

**Comment by greenrick** [comment]
@chrishoina @anooshapilli Hi Anoosha. Please close this issue. I have updated the lab to explain not to use spaces in Display Name, and not to use spaces nor underscores in Database Name:
**Display Name** - Enter a memorable name for the database for display purposes. For this lab, use ADW_Finance_Mart. (Spaces are not supported)
**Database Name** - Use letters and numbers only, starting with a letter. Maximum length is 14 characters. (Spaces and underscores not supported.) For this lab, use ADWFINANCE.

Chris, by the way, most of our Autonomous Database workshops are not using this adb-provision.md file for their provisioning lab. They are using either **adb-provision-conditional.md** in the same subfolder, or in the case of the "Autonomous Database 15 Minute Quick Start" workshop, the provisioning file at \adb\shared\adb-15-minutes\provision-database\adb-provision.moviestream.md. This markdown file points to re-usable "building blocks" markdown files stored in our GitHub's \common\building-blocks\tasks\adb subfolder.

**Comment by anooshapilli** [comment]
This issue is resolved.
